interface server {
    use player.{player};

    enum difficulty {
        peaceful,
        easy,
        normal,
        hard,
    }

    resource server {
        /// Returns the current difficulty level of the server
        get-difficulty: func() -> difficulty;

        /// Returns the total number of players connected across all worlds.
        get-player-count: func() -> u32;

        /// Returns the rolling average Milliseconds Per Tick (MSPT) over the last 100 ticks
        get-mspt: func() -> f64;

        /// Returns the effective Ticks Per Second (TPS)
        get-tps: func() -> f64;

        /// Returns all online players from all worlds on the server.
        get-all-players: func() -> list<player>;

        /// Searches for a player by their name across all worlds.
        get-player-by-name: func(name: string) -> option<player>;

        /// Searches for a player by their UUID across all worlds.
        get-player-by-uuid: func(id: string) -> option<player>;
    }
}
